

# coding: utf-8

Category.create(:name => 'グルメ', :parent_id => nil)
Category.create(:name => '和食・日本料理', :parent_id => 1)
Category.create(:name => '中華料理', :parent_id => 1)
Category.create(:name => 'フランス料理', :parent_id => 1)
Category.create(:name => 'トルコ料理', :parent_id => 1)
Category.create(:name => 'イタリア料理', :parent_id => 1)
Category.create(:name => 'タイ料理', :parent_id => 1)
Category.create(:name => '台湾料理', :parent_id => 1)
Category.create(:name => '韓国料理', :parent_id => 1)
Category.create(:name => '音楽', :parent_id => nil)
Category.create(:name => 'J-POP', :parent_id => 10)
Category.create(:name => 'K-POP', :parent_id => 10)
Category.create(:name => 'C-POP', :parent_id => 10)
Category.create(:name => 'VOCALOID', :parent_id => 10)
Category.create(:name => 'クラシック', :parent_id => 10)
Category.create(:name => 'J-ROCK', :parent_id => 10)
Category.create(:name => '演歌', :parent_id => 10)
Category.create(:name => 'エンターテイメント', :parent_id => nil)
Category.create(:name => '映画', :parent_id => 18)
Category.create(:name => 'ダンス・バレエ', :parent_id => 18)
Category.create(:name => '演劇・ミュージカル', :parent_id => 18)
Category.create(:name => 'お笑い', :parent_id => 18)
Category.create(:name => '漫画', :parent_id => 18)
Category.create(:name => 'アニメ', :parent_id => 18)
Category.create(:name => 'テーマパーク・遊園地', :parent_id => 18)
